version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    schedule:
      interval: weekly
    reviewers:
      - 'ViZhe'
    assignees:
      - 'ViZhe'
    labels:
      - 'pr: dependencies'
    commit-message:
      prefix: 'build'
      include: 'scope'
